version: "3.9"

services:
  db:
    image: postgres:16-alpine
    container_name: asklio-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h 127.0.0.1"]
      interval: 5s
      timeout: 3s
      retries: 10

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.3
    container_name: asklio-weaviate
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weavdata:/var/lib/weaviate
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/v1/.well-known/ready || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 20

  backend:
    build:
      context: ./asklio-procurement-backend
      dockerfile: Dockerfile
    container_name: asklio-backend
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      weaviate:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./asklio-procurement-backend/app:/app/app

  frontend:
    build:
      context: ./asklio-portal
      dockerfile: Dockerfile
    container_name: asklio-frontend
    ports:
      - "4200:80"
    depends_on:
      backend:
        condition: service_started

volumes:
  pgdata:
  weavdata: